# Generated by Django 3.0.6 on 2020-05-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User Info', 'verbose_name_plural': 'User Info'},
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=16, unique=True, verbose_name='Mobile phone number'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
